# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 332)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Window = QtWidgets.QFrame(self.centralwidget)
        self.Window.setGeometry(QtCore.QRect(10, 10, 741, 311))
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #3E2565;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 741, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #623AA3;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(701, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #623AA3;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #7A4FC1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(660, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #623AA3;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #7A4FC1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.ProgramLogsPlainTextEdit = QtWidgets.QPlainTextEdit(self.Window)
        self.ProgramLogsPlainTextEdit.setGeometry(QtCore.QRect(20, 50, 701, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProgramLogsPlainTextEdit.setFont(font)
        self.ProgramLogsPlainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    background-color: #623AA3;\n"
"}")
        self.ProgramLogsPlainTextEdit.setReadOnly(True)
        self.ProgramLogsPlainTextEdit.setObjectName("ProgramLogsPlainTextEdit")
        self.CreateCryptoKeyButton = QtWidgets.QPushButton(self.Window)
        self.CreateCryptoKeyButton.setGeometry(QtCore.QRect(20, 200, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CreateCryptoKeyButton.setFont(font)
        self.CreateCryptoKeyButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #C104A5;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #CF03B0;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #AF0396;\n"
"}")
        self.CreateCryptoKeyButton.setObjectName("CreateCryptoKeyButton")
        self.AddCryptoKeyButton = QtWidgets.QPushButton(self.Window)
        self.AddCryptoKeyButton.setGeometry(QtCore.QRect(20, 250, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddCryptoKeyButton.setFont(font)
        self.AddCryptoKeyButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #C104A5;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #CF03B0;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #AF0396;\n"
"}")
        self.AddCryptoKeyButton.setObjectName("AddCryptoKeyButton")
        self.AddFilesButton = QtWidgets.QPushButton(self.Window)
        self.AddFilesButton.setGeometry(QtCore.QRect(300, 200, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddFilesButton.setFont(font)
        self.AddFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #C104A5;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #CF03B0;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #AF0396;\n"
"}")
        self.AddFilesButton.setObjectName("AddFilesButton")
        self.EncryptFilesButton = QtWidgets.QPushButton(self.Window)
        self.EncryptFilesButton.setGeometry(QtCore.QRect(490, 200, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EncryptFilesButton.setFont(font)
        self.EncryptFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #C104A5;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #CF03B0;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #AF0396;\n"
"}")
        self.EncryptFilesButton.setObjectName("EncryptFilesButton")
        self.DecipherFilesButton = QtWidgets.QPushButton(self.Window)
        self.DecipherFilesButton.setGeometry(QtCore.QRect(490, 250, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DecipherFilesButton.setFont(font)
        self.DecipherFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #C104A5;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #CF03B0;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #AF0396;\n"
"}")
        self.DecipherFilesButton.setObjectName("DecipherFilesButton")
        self.RemoveFilesButton = QtWidgets.QPushButton(self.Window)
        self.RemoveFilesButton.setGeometry(QtCore.QRect(300, 250, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RemoveFilesButton.setFont(font)
        self.RemoveFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #C104A5;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #CF03B0;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #AF0396;\n"
"}")
        self.RemoveFilesButton.setObjectName("RemoveFilesButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CloseWindowButton.setText(_translate("MainWindow", "X"))
        self.MinimizeWindowButton.setText(_translate("MainWindow", "_"))
        self.ProgramLogsPlainTextEdit.setPlainText(_translate("MainWindow", "Ключ шифрования:\n"
"  • Отсутствует\n"
"\n"
"Файл(ы) для шифрования/расшифрования:\n"
"  • Отсутству(ет/ют)\n"
"\n"
"Последние действие:\n"
"  • Отсутству(ет/ют)"))
        self.CreateCryptoKeyButton.setText(_translate("MainWindow", "Создать ключ шифрования"))
        self.AddCryptoKeyButton.setText(_translate("MainWindow", "Добавить ключ шифрования"))
        self.AddFilesButton.setText(_translate("MainWindow", "Добавить файл(ы)"))
        self.EncryptFilesButton.setText(_translate("MainWindow", "Зашифровать файл(ы)"))
        self.DecipherFilesButton.setText(_translate("MainWindow", "Расшифровать файл(ы)"))
        self.RemoveFilesButton.setText(_translate("MainWindow", "Удалить файл(ы)"))
