# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 371)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Window = QtWidgets.QFrame(self.centralwidget)
        self.Window.setGeometry(QtCore.QRect(10, 10, 561, 351))
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #1B1D23;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    border: none;\n"
"    background: #595F76;\n"
"    width: 15px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical{    \n"
"    background-color: #494E61;\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::handle:vertical:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    border: none;\n"
"    background-color: #3A3F50;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    border: none;\n"
"    background-color: #3A3F50;\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal{\n"
"    border: none;\n"
"    background: #595F76;\n"
"    height: 15px;\n"
"    margin: 0px 15 0px 15;\n"
"    border-radius: opx;\n"
" }\n"
"\n"
"QScrollBar::handle:horizontal{    \n"
"    background-color: #494E61;\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal{\n"
"    border: none;\n"
"    background-color: #3A3F50;\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover{    \n"
"    background-color:#D5006A;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal{\n"
"    border: none;\n"
"    background-color: #3A3F50;\n"
"    width: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background: none;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 561, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #2C313C;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(521, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(480, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.ProgramLogsPlainTextEdit = QtWidgets.QPlainTextEdit(self.Window)
        self.ProgramLogsPlainTextEdit.setGeometry(QtCore.QRect(20, 40, 521, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ProgramLogsPlainTextEdit.setFont(font)
        self.ProgramLogsPlainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    background-color: #2C313C;\n"
"}")
        self.ProgramLogsPlainTextEdit.setReadOnly(True)
        self.ProgramLogsPlainTextEdit.setObjectName("ProgramLogsPlainTextEdit")
        self.CreateCryptoKeyButton = QtWidgets.QPushButton(self.Window)
        self.CreateCryptoKeyButton.setGeometry(QtCore.QRect(20, 190, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CreateCryptoKeyButton.setFont(font)
        self.CreateCryptoKeyButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.CreateCryptoKeyButton.setObjectName("CreateCryptoKeyButton")
        self.AddCryptoKeyButton = QtWidgets.QPushButton(self.Window)
        self.AddCryptoKeyButton.setGeometry(QtCore.QRect(20, 240, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddCryptoKeyButton.setFont(font)
        self.AddCryptoKeyButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.AddCryptoKeyButton.setObjectName("AddCryptoKeyButton")
        self.AddFilesButton = QtWidgets.QPushButton(self.Window)
        self.AddFilesButton.setGeometry(QtCore.QRect(20, 290, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddFilesButton.setFont(font)
        self.AddFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.AddFilesButton.setObjectName("AddFilesButton")
        self.EncryptFilesButton = QtWidgets.QPushButton(self.Window)
        self.EncryptFilesButton.setGeometry(QtCore.QRect(300, 190, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EncryptFilesButton.setFont(font)
        self.EncryptFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.EncryptFilesButton.setObjectName("EncryptFilesButton")
        self.DecipherFilesButton = QtWidgets.QPushButton(self.Window)
        self.DecipherFilesButton.setGeometry(QtCore.QRect(300, 240, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DecipherFilesButton.setFont(font)
        self.DecipherFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.DecipherFilesButton.setObjectName("DecipherFilesButton")
        self.RemoveFilesButton = QtWidgets.QPushButton(self.Window)
        self.RemoveFilesButton.setGeometry(QtCore.QRect(300, 290, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RemoveFilesButton.setFont(font)
        self.RemoveFilesButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.RemoveFilesButton.setObjectName("RemoveFilesButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CloseWindowButton.setText(_translate("MainWindow", "X"))
        self.MinimizeWindowButton.setText(_translate("MainWindow", "_"))
        self.ProgramLogsPlainTextEdit.setPlainText(_translate("MainWindow", "Ключ шифрования:\n"
"  • Отсутствует\n"
"\n"
"Файл(ы) для шифрования/расшифрования:\n"
"  • Отсутству(ет/ют)\n"
"\n"
"Последние действие:\n"
"  • Отсутству(ет/ют)"))
        self.CreateCryptoKeyButton.setText(_translate("MainWindow", "Создать ключ шифрования"))
        self.AddCryptoKeyButton.setText(_translate("MainWindow", "Добавить ключ шифрования"))
        self.AddFilesButton.setText(_translate("MainWindow", "Добавить файл(ы)"))
        self.EncryptFilesButton.setText(_translate("MainWindow", "Зашифровать файл(ы)"))
        self.DecipherFilesButton.setText(_translate("MainWindow", "Расшифровать файл(ы)"))
        self.RemoveFilesButton.setText(_translate("MainWindow", "Удалить файл(ы)"))
